codigo-fonte/trabalho-final/config/routes.rb
Rails.application.routes.draw do
  resources :queries
  resources :specialists
  resources :specialties
  devise_for :users, path: '', path_names: {
                                            sign_in: 'login',
                                            sign_up: 'register',
                                            sign_out: 'logout'
                                          }
  resources :exams
  resources :patients
  get 'escolherPaciente', controller: 'exams', action: 'escolherPaciente'
  get 'escolherPacienteAgenda', controller: 'queries', action: 'escolherPacienteAgenda'
  post 'custom_update', controller: 'exams', action: 'examesPaciente'
  post 'agenda_paciente', controller: 'queries', action: 'visualizarAgendaPaciente'
  post 'custom_att', controller: 'exams', action: 'tt'
  get 'home/index'
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

codigo-fonte/trabalho-final/app/models/patient.rb
class Patient < ApplicationRecord
  has_many :exam
  has_many :query
end

codigo-fonte/trabalho-final/app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Paciente cadastrado com sucesso.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Dados do paciente alterado com sucesso.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @exames_paciente = Exam.where("patient_id = ?", @patient["id"])

    @exames_paciente.each do |patient|
      if @patient!=nil
        redirect_to patients_path, flash: { error: "Não foi possível excluir paciente, pois o mesmo possui exames anexados." }
        return
      end
    end

    respond_to do |format|
      if @patient.destroy
        format.html { redirect_to patients_url, notice: 'Paciente deletado com sucesso.' }
        format.json { head :no_content }
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_patient
    @patient = Patient.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def patient_params
    params.require(:patient).permit(:name, :cpf, :age, :telefone, :email, :address, :profession)
  end
end

codigo-fonte/trabalho-final/app/helpers/patients_helper.rb
module PatientsHelper
end

codigo-fonte/trabalho-final/app/views/patients/_form.html.erb
<%= simple_form_for(@patient) do |f| %>
<%= f.error_notification %>
<%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

<div class="form-inputs">
  <%= f.input :name, label: false, input_html: { class: 'class="form-group col-lg-6', placeholder: "Nome" }%>
  <%= f.input :cpf, label: false, input_html: { class: 'class="form-group col-lg-3', placeholder: "CPF" }%>
  <%= f.input :age, label: false, end_year: Date.today.year - 100, start_year: Date.today.year%>
  <%= f.input :telefone, label: false, input_html: { class: 'class="form-group col-lg-3', placeholder: "Telefone" }%>
  <%= f.input :email, label: false, input_html: { class: 'class="form-group col-lg-5', placeholder: "E-mail" }%>
  <%= f.input :address, label: false, input_html: { class: 'class="form-group col-lg-5', placeholder: "Endereço" }%>
  <%= f.input :profession, label: false, input_html: { class: 'class="form-group col-lg-3', placeholder: "Profissão" }%>
</div>

<div class="form-actions">
  <%= f.button :submit, "Cadastrar", class: 'btn btn-success' %>
  <%= link_to 'Voltar', patients_path, class: 'btn btn-primary' %>
</div>
<br>

<% end %>

codigo-fonte/trabalho-final/app/views/patients/edit.html.erb
<div id="alinhaTabela">
  <br>
  <h1 id="p">Editar Dados Paciente</h1> <br>

  <%= render 'form', patient: @patient %>
  <br>
</div>

codigo-fonte/trabalho-final/app/views/patients/index.html.erb
<div id="alinhaTabela">
  <div class="row">
    <%= image_tag("/img/paciente.png") %>
    <div style="margin-top: 40px">
      <h1 id="p">Pacientes</h1>
    </div>
  </div>
  <br>
  <table class="table">
    <thead>
      <tr>
        <th>NOME</th>
        <th>CPF</th>
        <th>TELEFONE</th>
        <th>OPÇÕES</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.name %></td>
        <td><%= patient.cpf %></td>
        <td><%= patient.telefone %></td>
        <td><%= link_to 'Visualizar', patient %>
          <%= link_to 'Editar', edit_patient_path(patient) %>
          <%= link_to 'Deletar', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'Cadastrar Paciente', new_patient_path, class: 'btn btn-success' %>
  </div>

codigo-fonte/trabalho-final/app/views/patients/new.html.erb
<div id="alinhaTabela">
  <br>
  <h1 id="p">Novo Paciente</h1>
  <br>
  <%= render 'form', patient: @patient %>

</div>

codigo-fonte/trabalho-final/app/views/patients/show.html.erb
<div id="alinhaTabela">
  <br>
  <h2 id="p"> Dados do Paciente </h2>
  <br>
  <div class="row">
    <div class="form-group col-lg-5">
      <strong>Nome:</strong>
      <input type="text" class="form-control" name="endereco" value="<%= @patient.name %>" disabled>
    </div>

    <div class="form-group col-lg-3">
      <strong>CPF:</strong>
      <input type="text" class="form-control" name="endereco" value="<%= @patient.cpf %>" disabled>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-lg-3">
      <strong>Data Nascimento:</strong>
      <input type="text" class="form-control" name="endereco" value="<%= @patient.age.strftime("%d/%m/%Y")  %>" disabled>
    </div>

    <div class="form-group col-lg-3">
      <strong>Telefone:</strong>
      <input type="text" class="form-control" name="endereco" value="<%= @patient.telefone %>" disabled>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-lg-5">
      <strong>E-mail:</strong>
      <input type="text" class="form-control" name="endereco" value="<%= @patient.email %>" disabled>
    </div>  </div>

    <div class="row">
      <div class="form-group col-lg-5">
        <strong>Endereço:</strong>
        <input type="text" class="form-control" name="endereco" value="<%= @patient.address %>" disabled>
      </div>  </div>
      <div class="row">
        <div class="form-group col-lg-5">    <strong>Profissão:</strong>
          <input type="text" class="form-control" name="endereco" value="<%= @patient.profession %>" disabled>
        </div>  </div>
        <%= link_to 'Editar', edit_patient_path(@patient), class: "btn btn-primary" %>
        <%= link_to 'Voltar', patients_path, class: "btn btn-primary" %>
      </div>
<br>