codigo-fonte/trabalho-final/config/routes.rb
Rails.application.routes.draw do
  resources :queries
  resources :specialists
  resources :specialties
  devise_for :users, path: '', path_names: {
                                            sign_in: 'login',
                                            sign_up: 'register',
                                            sign_out: 'logout'
                                          }
  resources :exams
  resources :patients
  get 'escolherPaciente', controller: 'exams', action: 'escolherPaciente'
  get 'escolherPacienteAgenda', controller: 'queries', action: 'escolherPacienteAgenda'
  post 'custom_update', controller: 'exams', action: 'examesPaciente'
  post 'agenda_paciente', controller: 'queries', action: 'visualizarAgendaPaciente'
  post 'custom_att', controller: 'exams', action: 'tt'
  get 'home/index'
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

codigo-fonte/trabalho-final/app/models/exam.rb
class Exam < ApplicationRecord
  has_attached_file :exam, :styles => { :medium => "400x400>", :thumb => "120x90#", :grande => "600x700>" }
  validates_attachment_content_type :exam, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif", "application/pdf"]
  belongs_to :patient
end

codigo-fonte/trabalho-final/app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :set_exam, only: [:show, :edit, :update, :destroy]

  # GET /exams
  # GET /exams.json
  def index
    @exams = Exam.all
  end

  # GET /exams/1
  # GET /exams/1.json
  def show
  end

  def escolherPaciente
    @patients = Patient.all
    @patients = Patient.new
  end

  def examesPaciente
    @p = params[:paciente]
    @exame_paciente = Exam.where("patient_id = ?", @p["id"])
    @examepaciente = Exam.new
  end

def user_params
  params.require(:exam).permit(:id, :exam)
end

  # GET /exams/new
  def new
    @exam = Exam.new
  end

  # GET /exams/1/edit
  def edit
  end

  # POST /exams
  # POST /exams.json
  def create
    @exam = Exam.new(exam_params)
    respond_to do |format|
      if @exam.save
        format.html { redirect_to @exam, notice: 'Exame anexado com sucesso!' }
        format.json { render :show, status: :created, location: @exam }
      else
        format.html { render :examesPaciente }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exams/1
  # PATCH/PUT /exams/1.json
  def update
    respond_to do |format|
      if @exam.update(exam_params)
        format.html { redirect_to @exam, notice: 'Exam was successfully updated.' }
        format.json { render :show, status: :ok, location: @exam }
      else
        format.html { render :edit }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exams/1
  # DELETE /exams/1.json
  def destroy
    @exam.destroy
    respond_to do |format|
      format.html { redirect_to exams_url, notice: 'Exam was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exam
      @exam = Exam.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exam_params
      params.require(:exam).permit(:exam, :patient_id)
    end
end

codigo-fonte/trabalho-final/app/helpers/exams_helper.rb
module ExamsHelper
end

codigo-fonte/trabalho-final/app/views/exams/_form.html.erb
<%= simple_form_for(@exam) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :exam%>
    <%= f.association :patient %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

codigo-fonte/trabalho-final/app/views/exams/_formExames.html.erb
<%= simple_form_for(@examepaciente, :html => { :multipart => true }) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :exam, label: false, input_html: { class: 'class="form-control'}%>
    <%= f.hidden_field :patient_id, :value=>@p["id"]%>
  </div>

  <div class="form-actions">
    <%= submit_tag "Salvar imagem", class: "btn btn-success" %>
  </div> <br>
<% end %>

codigo-fonte/trabalho-final/app/views/exams/edit.html.erb
<h1>Editing Exam</h1>

<%= render 'form', exam: @exam %>

<%= link_to 'Show', @exam %> |
<%= link_to 'Back', exams_path %>

codigo-fonte/trabalho-final/app/views/exams/escolherPaciente.html.erb
<div id="alinhaTabela"> <br>

  <h1 id="p"> Escolha o Paciente </h1>

  <%= form_tag("/custom_update", method: "post") do %>

  <div class="form-group">
    <%= collection_select(:paciente, :id, Patient.all, :id, :name, :class => "form-control") %>
  </div>
  <%= submit_tag 'Visualizar Exames', :class => "btn btn-primary btn-lg btn-block" %>
  <% end %>

</div>

codigo-fonte/trabalho-final/app/views/exams/examesPaciente.html.erb
<div id="alinhaTabela">
  <br>
  <div class="form-inline">
    <a href="/escolherPaciente">
      <%= image_tag("/img/exame.png") %>
    </a>
    <h1 style="margin-top: 15px" id="p"> Exames </h1>
  </div> <br>

  <%= render 'formExames', exam: @exam %>

  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row">
        <% @exame_paciente.each do |exam| %>
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <%= image_tag(exam.exam.url(:medium)) %>
            <div class="card-body">
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <img class="img-responsive img-rounded" src="/img/lixeira.png" alt="" style="width: 30px; height: 30px;">
                </div>
              </div>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

codigo-fonte/trabalho-final/app/views/exams/index.html.erb
<h1>Exams</h1>

<table>
  <thead>
    <tr>
      <th>Exam</th>
      <th>Patient</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exams.each do |exam| %>
      <tr>
        <td><%= exam.exam %></td>
        <td><%= exam.patient %></td>
        <td><%= link_to 'Show', exam %></td>
        <td><%= link_to 'Edit', edit_exam_path(exam) %></td>
        <td><%= link_to 'Destroy', exam, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Exam', new_exam_path %>

codigo-fonte/trabalho-final/app/views/exams/new.html.erb
<div id="alinhaTabela">
  <h1 id="p">novo exame</h1>
  <br>
  <%= render 'form', patient: @exam %>

</div>

codigo-fonte/trabalho-final/app/views/exams/show.html.erb
<div id="alinhaTabela"> <br>
  <%= image_tag @exam.exam.url(:grande) %>
  <br><br>
  <%= link_to 'Voltar', escolherPaciente_path, class: 'btn btn-primary' %>
</div>