codigo-fonte/trabalho-final/config/routes.rb
Rails.application.routes.draw do
  resources :queries
  resources :specialists
  resources :specialties
  devise_for :users, path: '', path_names: {
                                            sign_in: 'login',
                                            sign_up: 'register',
                                            sign_out: 'logout'
                                          }
  resources :exams
  resources :patients
  get 'escolherPaciente', controller: 'exams', action: 'escolherPaciente'
  get 'escolherPacienteAgenda', controller: 'queries', action: 'escolherPacienteAgenda'
  post 'custom_update', controller: 'exams', action: 'examesPaciente'
  post 'agenda_paciente', controller: 'queries', action: 'visualizarAgendaPaciente'
  post 'custom_att', controller: 'exams', action: 'tt'
  get 'home/index'
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

codigo-fonte/trabalho-final/app/models/specialist.rb
class Specialist < ApplicationRecord
  belongs_to :specialty
  has_many :query
end

codigo-fonte/trabalho-final/app/controllers/specialists_controller.rb
class SpecialistsController < ApplicationController
  before_action :set_specialist, only: [:show, :edit, :update, :destroy]

  # GET /specialists
  # GET /specialists.json
  def index
    @specialists = Specialist.all
  end

  # GET /specialists/1
  # GET /specialists/1.json
  def show
  end

  # GET /specialists/new
  def new
    @specialist = Specialist.new
  end

  # GET /specialists/1/edit
  def edit
  end

  # POST /specialists
  # POST /specialists.json
  def create
    @specialist = Specialist.new(specialist_params)

    respond_to do |format|
      if @specialist.save
        format.html { redirect_to @specialist, notice: 'Especialista cadastrado com sucesso.' }
        format.json { render :show, status: :created, location: @specialist }
      else
        format.html { render :new }
        format.json { render json: @specialist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /specialists/1
  # PATCH/PUT /specialists/1.json
  def update
    respond_to do |format|
      if @specialist.update(specialist_params)
        format.html { redirect_to @specialist, notice: 'Dados do especialista alterado com sucesso.' }
        format.json { render :show, status: :ok, location: @specialist }
      else
        format.html { render :edit }
        format.json { render json: @specialist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /specialists/1
  # DELETE /specialists/1.json
  def destroy
    @consultas = Query.where("specialist_id = ?", @specialist["id"])

    @consultas.each do |consulta|
      if consulta!=nil
        redirect_to specialists_path, flash: { error: "Não foi possível excluir especialista, pois o mesmo possui consultas marcadas." }
        return
      end
    end

    @specialist.destroy
    respond_to do |format|
      format.html { redirect_to specialists_url, notice: 'Especialista excluído com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_specialist
      @specialist = Specialist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def specialist_params
      params.require(:specialist).permit(:name, :phone, :specialty_id)
    end
end

codigo-fonte/trabalho-final/app/helpers/specialists_helper.rb
module SpecialistsHelper
end

codigo-fonte/trabalho-final/app/views/specialists/_form.html.erb
<%= simple_form_for(@specialist) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name, label: "Nome:", input_html: { class: 'class="form-group col-lg-6'}%>
    <%= f.input :phone, label: "Telefone", input_html: { class: 'class="form-group col-lg-6'} %>
    <%= f.association :specialty, label: "Especialidade", input_html: { class: 'class="form-group col-lg-6'}%>
  </div>

  <div class="form-actions">
    <%= f.button :submit, 'Cadastrar', class: 'btn btn-success' %>
    <%= link_to 'Voltar', specialists_path, class: 'btn btn-primary'%>
  </div>
<% end %>

codigo-fonte/trabalho-final/app/views/specialists/edit.html.erb
<div id="alinhaTabela"><br>
  <h1 id="p">Editar Dados Especialista</h1><br>
  <%= render 'form', specialist: @specialist %>
</br>

codigo-fonte/trabalho-final/app/views/specialists/index.html.erb
<div id="alinhaTabela"><br>
  <div class="row">
    <%= image_tag("/img/especialista.png") %>
    <div style="margin-top: 40px">
      <h1 id="p">Especialistas</h1>
    </div>
  </div>
  <br>
  <table class="table">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Telefone</th>
      <th>Especialidade</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @specialists.each do |specialist| %>
      <tr>
        <td><%= specialist.name %></td>
        <td><%= specialist.phone %></td>
        <td><%= specialist.specialty["name"] %></td>
        <td><%= link_to 'Editar', edit_specialist_path(specialist) %></td>
        <td><%= link_to 'Deletar', specialist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Cadastrar Especialista', new_specialist_path, class: 'btn btn-success' %>

codigo-fonte/trabalho-final/app/views/specialists/new.html.erb
<div id="alinhaTabela">
  <br>
<h1 id="p">Novo Especialista</h1>

<%= render 'form', specialist: @specialist %>

</div>

codigo-fonte/trabalho-final/app/views/specialists/show.html.erb
<div id="alinhaTabela">
  <br>
  <h2 id="p"> Dados do Especialista </h2>
  <br>
  <div class="row">
    <div class="form-group col-lg-5">
      <strong>Nome:</strong>
      <input type="text" class="form-control" name="endereco" value="<%= @specialist.name %>" disabled>
    </div>
  </div>
  <div class="row">

    <div class="form-group col-lg-3">
      <strong>Telefone:</strong>
      <input type="text" class="form-control" name="endereco" value="<%= @specialist.phone %>" disabled>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-lg-3">
      <strong>Especialidade:</strong>
      <input type="text" class="form-control" name="endereco" value="<%= @specialist.specialty["name"] %>" disabled>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-lg-5">
      <%= link_to 'Editar', edit_specialist_path(@specialist), class: "btn btn-primary" %>
      <%= link_to 'Voltar', specialists_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>