codigo-fonte/trabalho-final/config/routes.rb
Rails.application.routes.draw do
  resources :queries
  resources :specialists
  resources :specialties
  devise_for :users, path: '', path_names: {
                                            sign_in: 'login',
                                            sign_up: 'register',
                                            sign_out: 'logout'
                                          }
  resources :exams
  resources :patients
  get 'escolherPaciente', controller: 'exams', action: 'escolherPaciente'
  get 'escolherPacienteAgenda', controller: 'queries', action: 'escolherPacienteAgenda'
  post 'custom_update', controller: 'exams', action: 'examesPaciente'
  post 'agenda_paciente', controller: 'queries', action: 'visualizarAgendaPaciente'
  post 'custom_att', controller: 'exams', action: 'tt'
  get 'home/index'
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

codigo-fonte/trabalho-final/app/models/query.rb
class Query < ApplicationRecord
  belongs_to :patient
  belongs_to :specialist
end

codigo-fonte/trabalho-final/app/controllers/queries_controller.rb
class QueriesController < ApplicationController
  before_action :set_query, only: [:show, :edit, :update, :destroy]

  # GET /queries
  # GET /queries.json
  def index
    @queries = Query.all
  end

  # GET /queries/1
  # GET /queries/1.json
  def show
  end

  # GET /queries/new
  def new
    @query = Query.new
  end

  # GET /queries/1/edit
  def edit
  end

  def escolherPacienteAgenda
    @patients = Patient.all
    @patients = Patient.new
  end

  def visualizarAgendaPaciente
    @p = params[:paciente]
    @agenda_paciente = Query.where("patient_id = ?", @p["id"])
    @agendapaciente = Query.new
  end

  # POST /queries
  # POST /queries.json
  def create
    @query = Query.new(query_params)

    @dataHora_escolhida = @query.date
    @especialista_escolhido = @query.specialist["id"]

    #verifica se já tem consulta na mesma data e hora, com o mesmo especialista
    @horarioDisponivel = Query.where("date = ?", @dataHora_escolhida).where("specialist_id = ?", @especialista_escolhido)

    @horarioDisponivel.each do |horario_disponivel|
      if horario_disponivel!=nil
        redirect_to queries_path, flash: { error: "Não foi possível agendar consulta, horário indiponível. Consulte a agenda." }
        return
      end
    end

    respond_to do |format|
      if @query.save
        format.html { redirect_to @query, notice: 'Consulta agendada com sucesso.' }
        format.json { render :show, status: :created, location: @query }
      else
        format.html { render :new }
        format.json { render json: @query.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /queries/1
  # PATCH/PUT /queries/1.json
  def update
    respond_to do |format|
      if @query.update(query_params)
        format.html { redirect_to @query, notice: 'Consulta atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @query }
      else
        format.html { render :edit }
        format.json { render json: @query.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /queries/1
  # DELETE /queries/1.json
  def destroy
    @query.destroy
    respond_to do |format|
      format.html { redirect_to queries_url, notice: 'Consulta deletada com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_query
    @query = Query.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def query_params
    params.require(:query).permit(:date, :status, :note, :patient_id, :specialist_id)
  end
end

codigo-fonte/trabalho-final/app/helpers/queries_helper.rb
module QueriesHelper
end

codigo-fonte/trabalho-final/app/views/queries/_form.html.erb
<%= simple_form_for(@query) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <%= f.input :date, label: "Data e Hora:", input_html: { class: 'class="form-group col-lg-2'}, end_year: Date.today.year - 0, start_year: Date.today.year%>
    <%= f.input :status, label: "Status:", input_html: { class: 'class="form-group col-lg-4' }%>
    <%= f.input :note, label: "Observação:", input_html: { class: 'class="form-group col-lg-4' }%>
    <%= f.association :patient, label: "Paciente:", input_html: { class: 'class="form-group col-lg-5'}%>
    <%= f.association :specialist, label: "Especialista", input_html: { class: 'class="form-group col-lg-5'}%>

  <div class="form-actions">
    <%= f.button :submit, "Agendar", class: 'btn btn-success' %>
    <%= link_to 'Voltar', queries_path, class: 'btn btn-primary' %>
  </div>
<% end %>

codigo-fonte/trabalho-final/app/views/queries/edit.html.erb
<div id="alinhaTabela">
  <br>
  <h1 id="p">Editar Dados Consulta</h1> <br>
  <%= render 'form', query: @query %>
  <br>
</div>

codigo-fonte/trabalho-final/app/views/queries/escolherPacienteAgenda.html.erb
<div id="alinhaTabela"> <br>

  <h1 id="p"> Escolha o Paciente </h1>

  <%= form_tag("/agenda_paciente", method: "post") do %>

  <div class="form-group">
    <%= collection_select(:paciente, :id, Patient.all, :id, :name, :class => "form-control") %>
  </div>
  <%= submit_tag 'Visualizar Agenda', :class => "btn btn-primary btn-lg btn-block" %>
  <% end %>

</div>

codigo-fonte/trabalho-final/app/views/queries/index.html.erb
<div id="alinhaTabela">
  <br>
  <div class="row">
    <%= image_tag("/img/agenda.png") %>
    <div style="margin-top: 40px">
      <h1 id="p">Consultas</h1>
    </div>
  </div>
  <br>
  <%= link_to 'Agendar Nova Consulta', new_query_path,  class: 'btn btn-success btn-lg btn-block' %> <br> <br>

  <table class="table">
    <thead>
      <tr>
        <th>DATA - HORA</th>
        <th>STATUS</th>
        <th>OBSERVAÇÃO</th>
        <th>PACIENTE</th>
        <th>ESPECIALIDADE</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @queries.each do |query| %>
      <tr>
        <td><%= query.date.strftime("%d/%m/%Y - %H:%M") %> </td>
        <td><%= query.status %></td>
        <td><%= query.note %></td>
        <td><%= query.patient["name"] %></td>
        <td><%= query.specialist.specialty["name"] %></td>
        <td><%= link_to 'Editar', edit_query_path(query) %></td>
        <td><%= link_to 'Deletar', query, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

codigo-fonte/trabalho-final/app/views/queries/new.html.erb
<div id="alinhaTabela">
  <br>
  <h1 id="p">Nova Consulta</h1>
  <br>
  <%= render 'form', query: @query %> <br>
</div>

codigo-fonte/trabalho-final/app/views/queries/show.html.erb
<div id="alinhaTabela">
  <br>
  <h2> Dados da Consulta </h2>
  <br>
  <div class="row">
    <div class="form-group col-lg-5">
      <strong>Data - Hora:</strong>
      <input type="text" class="form-control" name="endereco" value="<%= @query.date.strftime("%d/%m/%Y - %H:%M") %>" disabled>
    </div>

    <div class="form-group col-lg-3">
      <strong>Status:</strong>
      <input type="text" class="form-control" name="endereco" value="<%= @query.status %>" disabled>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-lg-3">
      <strong>Observação:</strong>
      <input type="text" class="form-control" name="endereco" value="<%= @query.note %>" disabled>
    </div>

    <div class="form-group col-lg-3">
      <strong>Paciente:</strong>
      <input type="text" class="form-control" name="endereco" value="<%= @query.patient["name"] %>" disabled>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-lg-5">
      <strong>Especialista:</strong>
      <input type="text" class="form-control" name="endereco" value="<%= @query.specialist["name"] %>" disabled>
    </div>  </div>

        <%= link_to 'Editar', edit_query_path(@query), class: "btn btn-primary" %>
        <%= link_to 'Voltar', queries_path, class: "btn btn-primary" %>
      </div>
<br>

codigo-fonte/trabalho-final/app/views/queries/visualizarAgendaPaciente.html.erb
<div id="alinhaTabela">
  <br>
  <div class="row">
    <%= image_tag("/img/agenda.png") %>
    <div style="margin-top: 40px">
      <h1 id="p"> Agenda Paciente <%= @p["name"] %></h1>
    </div>
  </div>
  <br>

  <table class="table">
    <thead>
      <tr>
        <th>DATA - HORA</th>
        <th>STATUS</th>
        <th>OBSERVAÇÃO</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @agenda_paciente.each do |query| %>
      <tr>
        <td><%= query.date.strftime("%d/%m/%Y - %H:%M") %> </td>
        <td><%= query.status %></td>
        <td><%= query.note %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'Voltar ao menu', root_path, class: "btn btn-primary" %> <br><br>
</div>